######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 14 19:34:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += streamdiff.cpp
